name: publish-beta

on:
  push:
    branches: [ main, dev ]
    paths:
        - 'DH.NRedis/**'
        - 'DH.NRedis.Extensions/**'
  workflow_dispatch:

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Build
      run: |
        dotnet pack --version-suffix $(date "+%Y.%m%d-beta%H%M") -c Release -o out DH.NRedis/DH.NRedis.csproj
        dotnet pack --version-suffix $(date "+%Y.%m%d-beta%H%M") -c Release -o out DH.NRedis.Extensions/DH.NRedis.Extensions.csproj
    - name: Publish
      run: |
        # dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/NewLifeX/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.chuangchu.net/v3/index.json --api-key ${{ secrets.mynugetKey }}